spring.application.name=pedidos-service
server.port=${SERVER_PORT:8083}

spring.datasource.url=${TT_DATASOURCE_URL}
spring.datasource.username=${TT_DATASOURCE_USERNAME}
spring.datasource.password=${TT_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
logging.level.org.springframework=INFO

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

ventas.service.base-url=${VENTAS_SERVICE_URL:http://localhost:8086}
productos.service.base-url=${PRODUCTOS_SERVICE_URL:http://localhost:8081}
usuarios.service.base-url=${USUARIOS_SERVICE_URL:http://localhost:8085}

pedidos.http-client.connect-timeout-ms=${HTTP_CLIENT_CONNECT_TIMEOUT_MS:2000}
pedidos.http-client.read-timeout-ms=${HTTP_CLIENT_READ_TIMEOUT_MS:5000}