spring.config.activate.on-profile=crdb

spring.datasource.url=${CRDB_DATASOURCE_URL:jdbc:postgresql://crdb-1:26257/tiendatech?sslmode=disable}
spring.datasource.username=${CRDB_DATASOURCE_USERNAME:root}
spring.datasource.password=${CRDB_DATASOURCE_PASSWORD:}
spring.datasource.hikari.transaction-isolation=TRANSACTION_SERIALIZABLE
spring.datasource.hikari.maximum-pool-size=${CRDB_POOL_MAX_SIZE:10}
spring.datasource.hikari.minimum-idle=${CRDB_POOL_MIN_IDLE:2}

crdb.retry.max-attempts=${CRDB_RETRY_MAX_ATTEMPTS:3}
crdb.retry.delay-ms=${CRDB_RETRY_DELAY_MS:100}

management.endpoints.web.exposure.include=health,prometheus
management.endpoints.web.path-mapping.prometheus=metrics
management.endpoint.health.show-details=always
management.metrics.enable.all=false
management.metrics.enable.crdb=true
