spring.config.activate.on-profile=crdb

spring.datasource.url=${CRDB_DATASOURCE_URL:jdbc:postgresql://crdb-1:26257/tiendatech?sslmode=disable}
spring.datasource.username=${CRDB_DATASOURCE_USERNAME:root}
spring.datasource.password=${CRDB_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.transaction-isolation=TRANSACTION_SERIALIZABLE
spring.sql.init.mode=never

management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/
management.endpoint.health.show-details=always
