services:
  productos-service:
    build:
      context: ./productos-service
    container_name: productos-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      TT_DATASOURCE_URL: ${TT_DATASOURCE_URL:-jdbc:postgresql://host.docker.internal:5432/TiendaTechV18}
      TT_DATASOURCE_USERNAME: ${TT_DATASOURCE_USERNAME:-postgres}
      TT_DATASOURCE_PASSWORD: ${TT_DATASOURCE_PASSWORD:-postgres}

  inventario-service:
    build:
      context: ./inventario-service
    container_name: inventario-service
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      TT_DATASOURCE_URL: ${TT_DATASOURCE_URL:-jdbc:postgresql://host.docker.internal:5432/TiendaTechV18}
      TT_DATASOURCE_USERNAME: ${TT_DATASOURCE_USERNAME:-postgres}
      TT_DATASOURCE_PASSWORD: ${TT_DATASOURCE_PASSWORD:-postgres}

  pedidos-service:
    build:
      context: ./pedidos-service
    container_name: pedidos-service
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      TT_DATASOURCE_URL: ${TT_DATASOURCE_URL:-jdbc:postgresql://host.docker.internal:5432/TiendaTechV18}
      TT_DATASOURCE_USERNAME: ${TT_DATASOURCE_USERNAME:-postgres}
      TT_DATASOURCE_PASSWORD: ${TT_DATASOURCE_PASSWORD:-postgres}


  ordenes-proveedores-service:
    build:
      context: ./ordenes-proveedores-service
    container_name: ordenes-proveedores-service
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      TT_DATASOURCE_URL: ${TT_DATASOURCE_URL:-jdbc:postgresql://host.docker.internal:5432/TiendaTechV18}
      TT_DATASOURCE_USERNAME: ${TT_DATASOURCE_USERNAME:-postgres}
      TT_DATASOURCE_PASSWORD: ${TT_DATASOURCE_PASSWORD:-postgres}
      INVENTARIO_SERVICE_URL: http://inventario-service:8082

  usuarios-service:
    build:
      context: ./usuarios
    container_name: usuarios-service
    ports:
      - "8085:8085"
    environment:
      SERVER_PORT: 8085
      TT_DATASOURCE_URL: ${TT_DATASOURCE_URL:-jdbc:postgresql://host.docker.internal:5432/TiendaTechV18}
      TT_DATASOURCE_USERNAME: ${TT_DATASOURCE_USERNAME:-postgres}
      TT_DATASOURCE_PASSWORD: ${TT_DATASOURCE_PASSWORD:-postgres}
      TT_MAIL_USERNAME: ${TT_MAIL_USERNAME}
      TT_MAIL_PASSWORD: ${TT_MAIL_PASSWORD}
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET}
      COOKIE_SECURE: ${COOKIE_SECURE:-false}
