<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { api } from '../services/api'
import { getUser } from '../services/session'
type Row=Record<string,unknown>
const router=useRouter(),profile=ref<Row>({}),addresses=ref<Row[]>([]),loading=ref(true),error=ref(''),saved=ref('')
const password=reactive({actual:'',nueva:'',repetir:''})
const field=(row:Row,...keys:string[])=>keys.map(k=>row[k]).find(v=>v!==undefined&&v!==null)
async function load(){const user=getUser();const id=user?.usuarioId??user?.id;if(!id){await router.push({path:'/login',query:{next:'/cuenta'}});return}try{profile.value=await api<Row>('/api/usuarios/me');const data=(profile.value.data as Row)||profile.value;profile.value=data;addresses.value=await api<Row[]>(`/api/usuarios/${id}/direcciones?view=full`).catch(()=>[])}catch(cause){error.value=cause instanceof Error?cause.message:'No se pudo cargar la cuenta.'}finally{loading.value=false}}
async function changePassword(){if(password.nueva!==password.repetir){error.value='Las contraseñas nuevas no coinciden.';return}try{await api('/api/seguridad/cambiar-password',{method:'POST',body:JSON.stringify({actual:password.actual,nueva:password.nueva})});saved.value='Contraseña actualizada.';password.actual=password.nueva=password.repetir=''}catch(cause){error.value=cause instanceof Error?cause.message:'No se pudo actualizar la contraseña.'}}
onMounted(load)
</script>
<template><section class="account-page"><header><p class="eyebrow">Mi TiendaTech</p><h1>Cuenta y preferencias</h1></header><p v-if="loading" class="status">Cargando tu cuenta…</p><p v-else-if="error&&!Object.keys(profile).length" class="alert">{{error}}</p><div v-else class="account-grid"><article class="account-card profile-card"><div class="avatar">{{String(field(profile,'nombre','usuario')||'U').charAt(0)}}</div><h2>{{field(profile,'nombre')}}</h2><p>@{{field(profile,'usuario')}}</p><dl><div><dt>Correo</dt><dd>{{field(profile,'correo')||'—'}}</dd></div><div><dt>Teléfono</dt><dd>{{field(profile,'telefono')||'—'}}</dd></div><div><dt>Cédula</dt><dd>{{field(profile,'cedula')||'—'}}</dd></div></dl></article><div class="account-stack"><article class="account-card"><div class="card-heading"><div><p class="eyebrow">Direcciones</p><h2>Puntos de entrega</h2></div><span>{{addresses.length}}</span></div><div v-if="addresses.length" class="address-list"><p v-for="(address,index) in addresses" :key="index"><strong>{{field(address,'calle')}}</strong><small>{{field(address,'ciudadNombre','ciudad')}} · {{field(address,'provinciaNombre','provincia')}}</small></p></div><p v-else class="muted">Todavía no tienes direcciones registradas.</p></article><form class="account-card" @submit.prevent="changePassword"><p class="eyebrow">Seguridad</p><h2>Cambiar contraseña</h2><div class="form-grid"><label>Contraseña actual<input v-model="password.actual" type="password" required /></label><label>Nueva contraseña<input v-model="password.nueva" type="password" minlength="8" required /></label><label>Repetir contraseña<input v-model="password.repetir" type="password" required /></label></div><p v-if="error" class="alert">{{error}}</p><p v-if="saved" class="success">{{saved}}</p><button class="button">Actualizar contraseña</button></form></div></div></section></template>
