import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../services/api'
import { cartLines, CartLine, currentCart, removeCartLine, updateCartLine } from '../services/cart'
import { getUser } from '../services/session'
import { imageFallback, money, productId, productImage, productName, Row } from './shared'
type DisplayLine = CartLine & { product?: Row; busy?: boolean }
export default function CartView() {
  const navigate = useNavigate(), [cartId, setCartId] = useState(0), [lines, setLines] = useState<DisplayLine[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('')
  useEffect(() => { void (async () => { if (!getUser()) { navigate('/login?next=%2Fcarrito'); return } try { const cart = await currentCart(); setCartId(cart.carritoId); const raw = await cartLines(cart.carritoId), catalog = await api<Row[]>('/api/productos?size=200').catch(() => []); setLines(await Promise.all(raw.map(async (line) => ({ ...line, product: await api<Row>(`/api/productos/${line.productoId}`).catch(() => catalog.find((row) => productId(row) === line.productoId)) })))) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo cargar el carrito.') } finally { setLoading(false) } })() }, [navigate])
  const subtotal = useMemo(() => lines.reduce((sum, line) => sum + Number(line.precioUnitario) * line.cantidad, 0), [lines])
  const busy = (product: number, value: boolean) => setLines((rows) => rows.map((row) => row.productoId === product ? { ...row, busy: value } : row))
  const change = async (line: DisplayLine, next: number) => { const quantity = Math.max(1, Math.min(99, next || 1)); busy(line.productoId, true); try { await updateCartLine(cartId, line.productoId, quantity); setLines((rows) => rows.map((row) => row.productoId === line.productoId ? { ...row, cantidad: quantity, busy: false } : row)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo actualizar la cantidad.'); busy(line.productoId, false) } }
  const remove = async (line: DisplayLine) => { busy(line.productoId, true); try { await removeCartLine(cartId, line.productoId); setLines((rows) => rows.filter((item) => item.productoId !== line.productoId)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo quitar el producto.'); busy(line.productoId, false) } }
  return <section className="cart-page"><div className="section-heading"><div><p className="eyebrow">Tu selección</p><h1>Carrito de compras</h1></div><Link className="back-link" to="/">← Seguir comprando</Link></div>{loading ? <p className="status">Cargando carrito…</p> : error && !lines.length ? <p className="alert">{error}</p> : lines.length ? <div className="cart-layout"><div className="cart-list">{lines.map((line) => <article key={line.productoId} className={`cart-line${line.busy ? ' busy' : ''}`}><img src={productImage(line.product)} alt={productName(line.product)} onError={imageFallback} /><div className="line-info"><Link to={`/producto/${line.productoId}`}><h2>{productName(line.product)}</h2></Link><p>{money(line.precioUnitario)} por unidad</p><button className="remove" onClick={() => void remove(line)}>Quitar</button></div><div className="quantity"><button onClick={() => void change(line, line.cantidad - 1)}>−</button><input value={line.cantidad} type="number" min="1" onChange={(e) => void change(line, Number(e.target.value))} /><button onClick={() => void change(line, line.cantidad + 1)}>+</button></div><strong>{money(Number(line.precioUnitario) * line.cantidad)}</strong></article>)}</div><aside className="summary"><h2>Resumen</h2><p><span>Productos</span><strong>{lines.reduce((sum, line) => sum + line.cantidad, 0)}</strong></p><p><span>Subtotal</span><strong>{money(subtotal)}</strong></p><p><span>Envío</span><strong>Por calcular</strong></p><div className="summary-total"><span>Total</span><strong>{money(subtotal)}</strong></div><Link className="button" to="/pago">Continuar al pago</Link></aside></div> : <div className="empty-cart"><span>🛒</span><h2>Tu carrito está vacío</h2><p>Encuentra componentes para tu próximo equipo.</p><Link className="button" to="/">Explorar productos</Link></div>}{error && lines.length > 0 && <p className="alert">{error}</p>}</section>
}
