<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { useRouter } from 'vue-router'
import { api,type PageResponse } from '../services/api'
import { cartLines,currentCart,type CartLine } from '../services/cart'
import { getUser } from '../services/session'
type Row=Record<string,unknown>
const router=useRouter(),lines=ref<CartLine[]>([]),addresses=ref<Row[]>([]),methods=ref<Row[]>([]),address=ref(''),method=ref(''),loading=ref(true),error=ref('')
const total=computed(()=>lines.value.reduce((s,l)=>s+Number(l.precioUnitario)*l.cantidad,0)),money=(v:number)=>v.toLocaleString('es-EC',{style:'currency',currency:'USD'})
async function load(){const user=getUser(),id=user?.usuarioId??user?.id;if(!id){await router.push({path:'/login',query:{next:'/pago'}});return}try{const cart=await currentCart();lines.value=await cartLines(cart.carritoId);addresses.value=await api<Row[]>(`/api/usuarios/${id}/direcciones?view=full`).catch(()=>[]);const methodsPage=await api<PageResponse<Row>>(`/api/metodopago/usuario/${id}`);methods.value=methodsPage.content}catch(cause){error.value=cause instanceof Error?cause.message:'No se pudo preparar el pago.'}finally{loading.value=false}}
onMounted(load)
</script>
<template><section class="checkout-page"><header><p class="eyebrow">Finalizar compra</p><h1>Revisa y confirma tu pedido</h1></header><p v-if="loading" class="status">Preparando el pago…</p><div v-else class="checkout-grid"><div><article class="account-card"><p class="eyebrow">Entrega</p><h2>Dirección</h2><select v-model="address"><option value="">Selecciona una dirección</option><option v-for="(item,index) in addresses" :key="index" :value="String(index)">{{item.calle}} · {{item.ciudadNombre||item.ciudad||''}}</option></select><p v-if="!addresses.length" class="muted">No hay direcciones disponibles. Puedes gestionarlas desde tu cuenta.</p><RouterLink to="/cuenta">Gestionar direcciones →</RouterLink></article><article class="account-card"><p class="eyebrow">Pago</p><h2>Método de pago</h2><select v-model="method"><option value="">Selecciona un método</option><option v-for="(item,index) in methods" :key="index" :value="String(index)">Tarjeta terminada en {{String(item.numeroTarjeta||'').slice(-4)}}</option></select><p v-if="!methods.length" class="muted">No hay métodos de pago registrados.</p></article></div><aside class="summary"><h2>Tu pedido</h2><p><span>Unidades</span><strong>{{lines.reduce((s,l)=>s+l.cantidad,0)}}</strong></p><p><span>Subtotal</span><strong>{{money(total)}}</strong></p><div class="summary-total"><span>Total</span><strong>{{money(total)}}</strong></div><button class="button" disabled>Pago pendiente de integración</button><small>La API de cobro no está disponible en los microservicios CRDB.</small></aside></div><p v-if="error" class="alert">{{error}}</p></section></template>
