import { FormEvent, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../services/api'
const initial = { nombre: '', usuario: '', correo: '', contrasena: '', repetir: '', cedula: '', telefono: '' }
export default function RegisterView() {
  const navigate = useNavigate(), [form, setForm] = useState(initial), [stage, setStage] = useState<'form'|'otp'|'done'>('form'), [otp, setOtp] = useState(''), [txId, setTxId] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }))
  const requestOtp = async (event: FormEvent) => { event.preventDefault(); setError(''); if (form.contrasena !== form.repetir) { setError('Las contraseñas no coinciden.'); return } if (!/^\d{10}$/.test(form.cedula) || !/^\d{10}$/.test(form.telefono)) { setError('Cédula y teléfono deben tener 10 dígitos.'); return } setBusy(true); try { const result = await api<{txId:string; devCode?:string}>('/api/otp', { method:'POST', body:JSON.stringify({ accion:'enviar', correo:form.correo, txId:txId || undefined }) }); setTxId(result.txId); setStage('otp'); if (result.devCode) setError(`SMTP bloqueado en esta red. Código de prueba: ${result.devCode}`) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo enviar el código.') } finally { setBusy(false) } }
  const verify = async () => { if (!/^\d{6}$/.test(otp)) { setError('Ingresa el código de 6 dígitos.'); return } setBusy(true); setError(''); try { await api('/api/otp', { method:'POST', body:JSON.stringify({ accion:'validar', correo:form.correo, codigo:otp, txId }) }); await api('/api/usuarios/crear', { method:'POST', body:JSON.stringify({ ...form, otpTxId:txId }) }); setStage('done'); window.setTimeout(() => navigate('/login'), 1400) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo crear la cuenta.') } finally { setBusy(false) } }
  const input = (key: keyof typeof form, type='text', extra: React.InputHTMLAttributes<HTMLInputElement>={}) => <input value={form[key]} onChange={(e) => update(key, e.target.value)} type={type} required {...extra} />
  return <section className="auth-page"><div className="auth-intro"><p className="eyebrow">Únete a TiendaTech</p><h1>Tu próximo equipo empieza con una cuenta.</h1><p>Guarda configuraciones, gestiona pedidos y compra componentes desde un solo lugar.</p></div>{stage === 'form' ? <form className="auth-form" onSubmit={requestOtp}><p className="eyebrow">Registro</p><h2>Crear cuenta</h2><div className="form-grid"><label>Nombre completo{input('nombre')}</label><label>Usuario{input('usuario')}</label><label>Correo{input('correo','email')}</label><label>Teléfono{input('telefono','text',{inputMode:'numeric',maxLength:10})}</label><label>Cédula{input('cedula','text',{inputMode:'numeric',maxLength:10})}</label><span></span><label>Contraseña{input('contrasena','password',{minLength:8})}</label><label>Repetir contraseña{input('repetir','password')}</label></div>{error && <p className="alert">{error}</p>}<button className="button" disabled={busy}>{busy ? 'Enviando…' : 'Verificar correo'}</button><p className="auth-switch">¿Ya tienes cuenta? <Link to="/login">Inicia sesión</Link></p></form> : stage === 'otp' ? <div className="auth-form compact"><p className="eyebrow">Verificación</p><h2>Revisa tu correo</h2><p>Enviamos un código de seis dígitos a <strong>{form.correo}</strong>.</p><label>Código<input value={otp} onChange={(e) => setOtp(e.target.value)} className="otp-input" inputMode="numeric" maxLength={6} /></label>{error && <p className="alert">{error}</p>}<button className="button" disabled={busy} onClick={() => void verify()}>{busy ? 'Validando…' : 'Crear mi cuenta'}</button><button className="link-button" onClick={() => setStage('form')}>Corregir datos</button></div> : <div className="auth-form compact success-panel"><span>✓</span><h2>Cuenta creada</h2><p>Te llevaremos al inicio de sesión.</p></div>}</section>
}
