spring.application.name=usuarios
server.port=8085

spring.datasource.url=${TT_DATASOURCE_URL}
spring.datasource.username=${TT_DATASOURCE_USERNAME}
spring.datasource.password=${TT_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.proc.param_null_passing=true
spring.jpa.properties.hibernate.default_schema=usuarios

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${TT_MAIL_USERNAME}
spring.mail.password=${TT_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

otp.ttl-minutes=10
otp.length=6
otp.resend.cooldown-seconds=60
otp.rate.max-per-15min=3

auth.access.minutes=10
auth.absolute.hours=8
auth.cookie.domain=localhost
auth.cookie.secure=false
auth.cookie.samesite=Lax
auth.jwt.secret=${AUTH_JWT_SECRET}

auth.idle.ADMIN=1
auth.idle.TRABAJADOR=1
auth.idle.CLIENTE=0

server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.secure=${COOKIE_SECURE:false}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.mail.enabled=false

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO

app.frontend.base-url=http://localhost:8080
app.upload-root=${APP_UPLOAD_ROOT:${user.dir}/uploads}
