spring.datasource.url=${CRDB_DATASOURCE_URL:jdbc:postgresql://localhost:26257/tiendatech?sslmode=disable}
spring.datasource.username=${CRDB_DATASOURCE_USERNAME:root}
spring.datasource.password=${CRDB_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
