-- TiendaTech - esquema distribuido para CockroachDB 23.2+
-- Entrega 3 / Modulo B
--
-- Patron dominante:
--   1. consultas de pedidos por trimestre;
--   2. historial de pedidos por usuario;
--   3. lectura conjunta de encabezado y detalle.
--
-- La columna `fecha` del modelo implementado corresponde a `fecha_pedido`
-- en la guia de la Entrega 3.

CREATE DATABASE IF NOT EXISTS tiendatech;
USE tiendatech;

CREATE SCHEMA IF NOT EXISTS usuarios;
CREATE SCHEMA IF NOT EXISTS pedidos;
CREATE SCHEMA IF NOT EXISTS ventas;

CREATE TABLE IF NOT EXISTS usuarios.usuario (
    usuario_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    correo STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id),
    CONSTRAINT uq_usuario_correo UNIQUE (correo)
);

-- `fecha` encabeza la PK porque CockroachDB requiere que las columnas de
-- particionamiento formen un prefijo de la clave primaria.
CREATE TABLE IF NOT EXISTS pedidos.orden (
    fecha DATE NOT NULL,
    orden_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    usuario_id INT8 NOT NULL,
    direccion_id INT8,
    metodopago_id INT8,
    subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
    total DECIMAL(18,2) NOT NULL DEFAULT 0,
    estado STRING NOT NULL DEFAULT 'CREADA',
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_orden PRIMARY KEY (fecha, orden_id),
    CONSTRAINT fk_orden_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios.usuario (usuario_id),
    CONSTRAINT ck_orden_total_no_negativo CHECK (total >= 0),
    UNIQUE INDEX uq_orden_id (orden_id),
    INDEX idx_orden_usuario_fecha (usuario_id, fecha DESC)
        STORING (estado, total)
);

-- El dataset analitico usa los IDs 1..500000. La secuencia avanza desde el
-- mayor ID existente o desde 1000000, sin retroceder al reaplicar el esquema.
SELECT setval(
    'pedidos.orden_orden_id_seq',
    greatest(coalesce((SELECT max(orden_id) FROM pedidos.orden), 0), 1000000)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_orden_id ON pedidos.orden (orden_id);

CREATE TABLE IF NOT EXISTS pedidos.carrito_de_compra (
    carrito_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    usuario_id INT8 NOT NULL,
    total DECIMAL(18,2) NOT NULL DEFAULT 0,
    habilitado BOOL NOT NULL DEFAULT true,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_carrito PRIMARY KEY (carrito_id),
    CONSTRAINT fk_carrito_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios.usuario (usuario_id),
    INDEX idx_carrito_usuario_habilitado (usuario_id, habilitado)
);

CREATE TABLE IF NOT EXISTS pedidos.carrito_detalle (
    carrito_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    cantidad INT4 NOT NULL,
    precio_unitario DECIMAL(18,2) NOT NULL,
    CONSTRAINT pk_carrito_detalle PRIMARY KEY (carrito_id, producto_id),
    CONSTRAINT fk_carrito_detalle
        FOREIGN KEY (carrito_id)
        REFERENCES pedidos.carrito_de_compra (carrito_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_carrito_cantidad_positiva CHECK (cantidad > 0)
);

-- Fila aislada para demostrar de forma controlada una colision SERIALIZABLE.
-- No participa en el flujo funcional ni altera datos de negocio.
CREATE TABLE IF NOT EXISTS pedidos.retry_probe (
    probe_id INT8 NOT NULL,
    valor INT8 NOT NULL DEFAULT 0,
    CONSTRAINT pk_retry_probe PRIMARY KEY (probe_id)
);
UPSERT INTO pedidos.retry_probe (probe_id, valor) VALUES (1, 0);

CREATE TABLE IF NOT EXISTS pedidos.detalle_orden (
    fecha DATE NOT NULL,
    detalle_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    orden_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    cantidad INT4 NOT NULL,
    precio_unitario DECIMAL(18,2) NOT NULL,
    subtotal DECIMAL(18,2) NOT NULL,
    iva DECIMAL(18,2) NOT NULL,
    total DECIMAL(18,2) NOT NULL,
    CONSTRAINT pk_detalle_orden PRIMARY KEY (fecha, detalle_id),
    CONSTRAINT fk_detalle_orden
        FOREIGN KEY (fecha, orden_id)
        REFERENCES pedidos.orden (fecha, orden_id),
    CONSTRAINT ck_detalle_cantidad_positiva CHECK (cantidad > 0),
    INDEX idx_detalle_orden (fecha, orden_id),
    INDEX idx_detalle_producto_fecha (producto_id, fecha DESC)
);

CREATE TABLE IF NOT EXISTS ventas.factura_encabezado (
    factura_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    orden_id INT8 NOT NULL,
    fecha_orden DATE NOT NULL,
    usuario_id INT8 NOT NULL,
    fecha_emision DATE NOT NULL DEFAULT current_date(),
    subtotal DECIMAL(18,2) NOT NULL,
    total DECIMAL(18,2) NOT NULL,
    numero STRING NOT NULL,
    CONSTRAINT pk_factura PRIMARY KEY (factura_id),
    CONSTRAINT uq_factura_orden UNIQUE (orden_id),
    CONSTRAINT uq_factura_numero UNIQUE (numero),
    CONSTRAINT fk_factura_orden
        FOREIGN KEY (fecha_orden, orden_id)
        REFERENCES pedidos.orden (fecha, orden_id)
);

CREATE TABLE IF NOT EXISTS ventas.factura_cuerpo (
    factura_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    nombre_producto STRING NOT NULL,
    cantidad INT4 NOT NULL,
    precio DECIMAL(18,2) NOT NULL,
    subtotal DECIMAL(18,2) NOT NULL,
    iva DECIMAL(18,2) NOT NULL,
    total DECIMAL(18,2) NOT NULL,
    CONSTRAINT pk_factura_cuerpo PRIMARY KEY (factura_id, producto_id),
    CONSTRAINT fk_factura_cuerpo
        FOREIGN KEY (factura_id)
        REFERENCES ventas.factura_encabezado (factura_id)
        ON DELETE CASCADE
);

-- Fragmentación horizontal física por límites trimestrales. SPLIT AT crea
-- límites de rango reproducibles sin requerir una licencia Enterprise.
ALTER TABLE pedidos.orden SPLIT AT VALUES
    ('2026-01-01'),
    ('2026-04-01'),
    ('2026-07-01'),
    ('2026-10-01'),
    ('2027-01-01');

ALTER TABLE pedidos.detalle_orden SPLIT AT VALUES
    ('2026-01-01'),
    ('2026-04-01'),
    ('2026-07-01'),
    ('2026-10-01'),
    ('2027-01-01');

ALTER TABLE pedidos.orden SCATTER;
ALTER TABLE pedidos.detalle_orden SCATTER;

-- Replicacion de tres copias: con quorum mayoritario, el rango tolera
-- la perdida de una replica. La prueba con dos nodos debe perder disponibilidad.
ALTER RANGE default CONFIGURE ZONE USING num_replicas = 3;

-- Consultas de referencia para el protocolo experimental.
-- Top-N de productos por trimestre:
-- SELECT producto_id, sum(cantidad) AS unidades
-- FROM pedidos.detalle_orden
-- WHERE fecha >= $1 AND fecha < $2
-- GROUP BY producto_id
-- ORDER BY unidades DESC
-- LIMIT 10;
--
-- Historial colocalizable por el indice (usuario_id, fecha):
-- SELECT fecha, orden_id, estado, total
-- FROM pedidos.orden
-- WHERE usuario_id = $1
-- ORDER BY fecha DESC;
