-- TiendaTech - esquema distribuido para CockroachDB 23.2+
-- Entrega 3 / Modulo B
--
-- Patron dominante:
--   1. consultas de pedidos por trimestre;
--   2. historial de pedidos por usuario;
--   3. lectura conjunta de encabezado y detalle.
--
-- La columna `fecha` del modelo implementado corresponde a `fecha_pedido`
-- en la guia de la Entrega 3.

CREATE DATABASE IF NOT EXISTS tiendatech;
USE tiendatech;

CREATE SCHEMA IF NOT EXISTS usuarios;
CREATE SCHEMA IF NOT EXISTS pedidos;

CREATE TABLE IF NOT EXISTS usuarios.usuario (
    usuario_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    nombre STRING NOT NULL,
    correo STRING NOT NULL,
    habilitado BOOL NOT NULL DEFAULT true,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id),
    CONSTRAINT uq_usuario_correo UNIQUE (correo)
);

-- `fecha` encabeza la PK porque CockroachDB requiere que las columnas de
-- particionamiento formen un prefijo de la clave primaria.
CREATE TABLE IF NOT EXISTS pedidos.orden (
    fecha DATE NOT NULL,
    orden_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    usuario_id INT8 NOT NULL,
    direccion_id INT8,
    metodopago_id INT8,
    subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
    total DECIMAL(18,2) NOT NULL DEFAULT 0,
    estado STRING NOT NULL DEFAULT 'CREADA',
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_orden PRIMARY KEY (fecha, orden_id),
    CONSTRAINT fk_orden_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios.usuario (usuario_id),
    CONSTRAINT ck_orden_total_no_negativo CHECK (total >= 0),
    INDEX idx_orden_id (orden_id),
    INDEX idx_orden_usuario_fecha (usuario_id, fecha DESC)
        STORING (estado, total)
);

CREATE TABLE IF NOT EXISTS pedidos.detalle_orden (
    fecha DATE NOT NULL,
    detalle_id INT8 GENERATED BY DEFAULT AS IDENTITY,
    orden_id INT8 NOT NULL,
    producto_id INT8 NOT NULL,
    cantidad INT4 NOT NULL,
    precio_unitario DECIMAL(18,2) NOT NULL,
    subtotal DECIMAL(18,2) NOT NULL,
    iva DECIMAL(18,2) NOT NULL,
    total DECIMAL(18,2) NOT NULL,
    CONSTRAINT pk_detalle_orden PRIMARY KEY (fecha, detalle_id),
    CONSTRAINT fk_detalle_orden
        FOREIGN KEY (fecha, orden_id)
        REFERENCES pedidos.orden (fecha, orden_id),
    CONSTRAINT ck_detalle_cantidad_positiva CHECK (cantidad > 0),
    INDEX idx_detalle_orden (fecha, orden_id),
    INDEX idx_detalle_producto_fecha (producto_id, fecha DESC)
);

-- Fragmentación horizontal física por límites trimestrales. SPLIT AT crea
-- límites de rango reproducibles sin requerir una licencia Enterprise.
ALTER TABLE pedidos.orden SPLIT AT VALUES
    ('2026-01-01'),
    ('2026-04-01'),
    ('2026-07-01'),
    ('2026-10-01'),
    ('2027-01-01');

ALTER TABLE pedidos.detalle_orden SPLIT AT VALUES
    ('2026-01-01'),
    ('2026-04-01'),
    ('2026-07-01'),
    ('2026-10-01'),
    ('2027-01-01');

ALTER TABLE pedidos.orden SCATTER;
ALTER TABLE pedidos.detalle_orden SCATTER;

-- Replicacion de tres copias: con quorum mayoritario, el rango tolera
-- la perdida de una replica. La prueba con dos nodos debe perder disponibilidad.
ALTER RANGE default CONFIGURE ZONE USING num_replicas = 3;

-- Consultas de referencia para el protocolo experimental.
-- Top-N de productos por trimestre:
-- SELECT producto_id, sum(cantidad) AS unidades
-- FROM pedidos.detalle_orden
-- WHERE fecha >= $1 AND fecha < $2
-- GROUP BY producto_id
-- ORDER BY unidades DESC
-- LIMIT 10;
--
-- Historial colocalizable por el indice (usuario_id, fecha):
-- SELECT fecha, orden_id, estado, total
-- FROM pedidos.orden
-- WHERE usuario_id = $1
-- ORDER BY fecha DESC;
